name: Staging Build2
run-name:  "ArtifactID: ${{ github.run_id }}"

on:
  workflow_dispatch:
    inputs:
      status_code:
        description: Status Code
        type: string
        default: True
        

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ' build compelted '
          [ "True" != "${{ github.event.inputs.status_code }}" ] && exist 1
     














